album_data = [
    {"artist": "Debra DiGiovanni", "track": "So Efficient"},
    {"artist": "Debra DiGiovanni", "track": "Hotels, Catchers Mitts and Bidets!"},
    {"artist": "Debra DiGiovanni", "track": "A Reasonable Hour"},
    {"artist": "Debra DiGiovanni", "track": "War for Water"},
    {"artist": "Debra DiGiovanni", "track": "Excited to Lie"},
    {"artist": "Debra DiGiovanni", "track": "The Message is Love"},
    {"artist": "Debra DiGiovanni", "track": "Very Seductive"},
    {"artist": "Debra DiGiovanni", "track": "Black Coffee"},
    {"artist": "Debra DiGiovanni", "track": "Where Did it Go?!"},
    {"artist": "Debra DiGiovanni", "track": "Very Refreshing!"},
    {"artist": "Debra DiGiovanni", "track": "Q and A"},
    {"artist": "Debra DiGiovanni", "track": "Doing Some Research"},
    {"artist": "Debra DiGiovanni", "track": "In Between Cats"},
    {"artist": "Debra DiGiovanni", "track": "Not a Picky Woman"},
    {"artist": "Debra DiGiovanni", "track": "Snoozapalooza"},
    {"artist": "Debra DiGiovanni", "track": "Double Breakfast!"},
    {"artist": "Debra DiGiovanni", "track": "Get the Hose"},
    {"artist": "Debra DiGiovanni", "track": "Human Man"},
    {"artist": "Debra DiGiovanni", "track": "Honourable Intentions"},
    {"artist": "Debra DiGiovanni", "track": "No Segues"},

    {"artist": "Howie Mandel", "track": "Voices"},
    {"artist": "Howie Mandel", "track": "Always"},
    {"artist": "Howie Mandel", "track": "Nut Cream"},
    {"artist": "Howie Mandel", "track": "High School"},
    {"artist": "Howie Mandel", "track": "43 Years"},

    {"artist": "Darcy and Jer", "track": "Pop Quiz"},
    {"artist": "Darcy and Jer", "track": "Who are Darcy and Jer?"},
    {"artist": "Darcy and Jer", "track": "20th Anniversary"},
    {"artist": "Darcy and Jer", "track": "He Stole My Life"},
    {"artist": "Darcy and Jer", "track": "Mentally Unwell"},
    {"artist": "Darcy and Jer", "track": "ADHD Halftime Stretch"},
    {"artist": "Darcy and Jer", "track": "Fagoote"},
    {"artist": "Darcy and Jer", "track": "That Bitch Covid"},
    {"artist": "Darcy and Jer", "track": "Diet Culture Is BS"},
    {"artist": "Darcy and Jer", "track": "Going To Bed In Your 40s"},
    {"artist": "Darcy and Jer", "track": "We Got Old"},
    {"artist": "Darcy and Jer", "track": "Buying A House"},
    {"artist": "Darcy and Jer", "track": "Agreeable Jer"},
    {"artist": "Darcy and Jer", "track": "Married Life"},
    {"artist": "Darcy and Jer", "track": "Yuma"},
    {"artist": "Darcy and Jer", "track": "Busy Donkey"},
    {"artist": "Darcy and Jer", "track": "Darcy's Favourite Plant"},
    {"artist": "Darcy and Jer", "track": "Getting My Husband Stoned"},

    {"artist": "D.J. Demers", "track": "Talking Time is Over"},
    {"artist": "D.J. Demers", "track": "A Quiet Beef"},
    {"artist": "D.J. Demers", "track": "I'm a Pacifist"},
    {"artist": "D.J. Demers", "track": "We're Going with the Juggler"},
    {"artist": "D.J. Demers", "track": "Is He Gonna Fight Me?"},
    {"artist": "D.J. Demers", "track": "Whistle While You Work"},
    {"artist": "D.J. Demers", "track": "Catch You in the Other Side, Brother"},
    {"artist": "D.J. Demers", "track": "Atonement"},
    {"artist": "D.J. Demers", "track": "Chit Chat Bit"},
    {"artist": "D.J. Demers", "track": "That Looks Comfortable"},
    {"artist": "D.J. Demers", "track": "This Guy's My Leader"},
    {"artist": "D.J. Demers", "track": "Vanguard Again?"},
    {"artist": "D.J. Demers", "track": "Stop Admonishing Me"},
    {"artist": "D.J. Demers", "track": "For This Exact Situation, I Believe"}
    

]